DROP DATABASE IF EXISTS TITANICS;
CREATE DATABASE TITANICS;
USE TITANICS;

DROP TABLE IF EXISTS TITANICTEST;

CREATE TABLE TITANICTEST (
  PASSENGERID INT,
  PCLASS INT,
  NAME VARCHAR(255) NULL,
  SEX Varchar(8) NOT NULL,
  AGE FLOAT,
  SIBSP int,
  PARCH int,
  TICKET varchar(100),
  FARE dec(6,4),
  CARBIN varchar(255),
  EMBARKED varchar(100)
  );
  
LOAD DATA LOCAL INFILE 'c:/Users/m/Desktop/test.csv' 
INTO TABLE TITANICTEST 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM TITANICTEST;


SELECT DISTINCT CLASS.NAME AS NAME, FARE.FARE AS FARE,
CLASS.SEX AS SEX, FARE.TICKET AS TICKET
  FROM TITANICTEST CLASS
       JOIN TITANICTEST FARE
       ON FARE.AGE = CLASS.FARE
	   JOIN TITANICTEST CABIN
       ON CLASS.SIBSP = CABIN.PARCH
       GROUP BY FARE.FARE <> '50'
ORDER BY NAME, TICKET, SEX ASC;